- public/js/client.js
#deeppink was being odd, getting match for being in the #[\da-f]{3} patern
> fixing color parsing

- public/help/index.html
Slight clean up. I wasn't sure what you wanted.
> What are you telling me to do? I don't comprehendo.

- public/js/client.js
I tested it locally and have added the stuff manually ON THE CURRENT COMMIT. Push away
> Adds message quoting! Finally! 100% safe

- public/js/client.js
This has been tested locally on the latest git push.
> Added feature: Clicking message inputs it's ID into your bar.

- public/js/client.js
-Hovering over text displays message. I am CERTAIN this is safe as it appends it to the messages body, so everything renders.
Uses html onmouseenter, onmousemove and jquery, all safe.
-Now, the message number only shows when hovering over the timestamp, as it doesn't matter anymore
-You can quote multiple messages, and they all show stuff when hovering!
-Invalid links are red with no underline
-Clicking the timestamp no longer replaces your whole message (as suggested by bruno)
There is a tiny glitch right now that shows the scrollbar for a split second while you're hovering sometimes, i expect no problems.
I used .prepend() to the messages element, but it used a setTimeout so that you don't see it being appended, only after.
That's all. Thanks.
> Hovering now works, among other things! (100% safe)

- server.js
Should work. Uses a for-in loop now.
Also displays the ip, INCLUDING those logged in before. So super secure.
And you can just ban an ip if they spam.
> External logger detector. It's safe, i think.

- server.js
fixing some *-message problems
> random things

- public/css/client.css
- public/js/client.js
- server.js
This adds the type of message "alert-message", right now just used for when there are silent loggers. Note this is just a type of message, not the logger disc. mechanism itself.
> Randoms dude add alerts

- public/css/client.css
- public/js/client.js
- server.js
Second because the first became outdated.
Adds punching.
http://gyazo.com/5632dfbe373a989ccb6ed725c07c9dc0
> Randoms dude punches2

- public/js/client.js
- server.js
Well. Tokens. As suggested by Bruno.
> Randoms dude tokens

- server.js
> Revert "Randoms dude tokens"

- public/js/client.js
- server.js
This is the last pull I will do outside of the dev branch. Again, it's bruno's idea that i implemented. **It actually works.**
> Randoms dude tokens working

- README.md
Also made the file a bit prettier
> Add committing instructions

- server.js
Fix tokens, based on user's nick so now you can login to multiple accounts.
> Fixed tokens

- public/js/client.js
- server.js
Changes:
- Banip works now
- /afk command
- no POP when saying own name
- Quotes are formatted by themselves, it inserts or leaves your spaces so they format correct
- Private/public channels
- Block command fixed
- Ctrl+hover doesn't scroll down on images
Removals
-Whitelisting replaced by private channels
> Capri (3.0.10)

- index.html
- public/css/client.css
- public/js/client.js
- server.js
Ecru is a pallid shade of brown. This update is not pallid. Contributors include sammich and Randomguy_.
Updates:
- New font Droid Sans
- You can maximize images and the UI won't scroll
- /logout command
Fixes:
- Whitelist commands renamed, and issues fixed
- login with no slash now does not submit!
- cannot lock or unlock repeatedly
- /hlist is invalid, /help and /menu now!
Removals:
- Spinner style
> Ecru (3.2.21)

- index.html
Reverts InfraRaven/spooks-chatjs#271 Try again
> Revert "Webcam div complete"

- index.html
> Div&script

- public/js/client.js
Reverts InfraRaven/spooks-chatjs#276
I think infra was displeased Mr.Guy
> Revert "Cam"

- index.html
Reverts InfraRaven/spooks-chatjs#276
I think infra was displeased Mr.Guy
> Revert "Div&script"

- public/css/client.css
Used box shadows to add a bit of specularity, gloss, and diffuse to the shadows. Also, switched from names to transparent colors, so it looks less dark, but will still work with alternative /themes. 
I checked ahead of time this time, heh. It won't be shit, promise. 
ily mang.
plz merge upstream
> Uniformed the Button with the rest of the UI.

- public/js/client.js
The Menu now goes down when it's at the top of the screen.
Beta tested in advance, but I'd like to see it in practice on 2s4.me first.
> Fixed the Menu.

- public/css/client.css
It now matches the spooks theme, and it's done to your specs. Unless your screen has a built in grunge filter though, it won't look exactly the same as the PSD. Well, we could use image files, but those are bloat.
> Fixed the Menu's CSS.

- public/css/client.css
Most of the work is here. I just have to add a class="top" in the html now.
If this isn't done, we'll have a mild visual glitch. 
Don't worry though, Infra. Eleven bytes away from success!
> Part one of my Video Embed Fix

- public/js/client.js
Everything is work now. 
Merge and everything will be donezors.
> And, part2.

- public/js/client.js
> Fixed the Video Overlay's re-sizing error

- public/js/client.js
Used backgroundColor : to give the container a background color of dark grey.
> Fixes that other thing.

- public/css/client.css
Oh wait, I can merge my self, kek.
> deleted those shadows for you, infra.

- README.md
- public/js/client.js
- server.js
Reverts InfraRaven/spooks-chatjs#323
> Revert "Dev"
